### ISSUE TITLE
Template not rendered at all. Cannot call method 'replace' of undefined in jade.js (v1.4.1)

### ISSUE THREAD

**Issue by Rhizosis** [jadejs/jade#1601]
When a sole dot is added at the end of the line describing the element, without adding an extra css class identifier jade will refuse to render any out and will generate a white page. This only happens when the next line has the same indentation level as the current line with the colon at the end. Please observe the following usecase.

Reproducible with:

## Node in console debugging on
```javascript
var jade = require('jade')
jade.render("h2.text-center.\nh3\n\tHello", {debug: true});
```

### Output:
```javascript
TypeError: Cannot call method 'replace' of undefined
    at parse (/storage/dev/node_modules/jade/lib/jade.js:114:71)
    at Object.exports.compile (/storage/dev/node_modules/jade/lib/jade.js:161:16)
    at Object.exports.render (/storage/dev/node_modules/jade/lib/jade.js:272:15)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
```

## Node in console debugging off
```javascript
var jade = require('jade')
jade.render("h2.text-center.\nh3\n\tHello", {debug: false});
```

### Output:
```javascript
''
```

When removing the dot at the end of the 'h2' line or when adding an indented level of text in the 'h2' tag, it will work fine.
However if the next line has the same indentation level as the h2, no output is generated.

**Comment by ForbesLindesay** [comment]
This is fixed in the latest version of jade.
