### ISSUE TITLE
Clearer error message than: unexpected token "indent"

### ISSUE THREAD

**Issue by bitfinity** [jadejs/jade#1646]
When you have a script tag and you don't indent one more level, you get that error.  It is actually the opposite of what the error is.  The error is a missing tab or indent.

**Comment by TimothyGu** [comment]
```sh
$ echo '
>     script.
>     $(function() {
>           $("#phone").mask("(999) 999-9999");
>     });
> ' | bin/jade.js
```

```
/home/timothy_gu/jade/lib/runtime.js:231
  throw err;
        ^
Error: Jade:2
    1| 
  > 2|     script.
    3|     $(function() {
    4|           $("#phone").mask("(999) 999-9999");
    5|     });

unexpected token "indent"
    at Parser.parseExpr (/home/timothy_gu/jade/lib/parser.js:252:15)
    at Parser.parse (/home/timothy_gu/jade/lib/parser.js:122:25)
    at parse (/home/timothy_gu/jade/lib/index.js:102:21)
    at Object.exports.compile (/home/timothy_gu/jade/lib/index.js:177:16)
    at Socket.<anonymous> (/home/timothy_gu/jade/bin/jade.js:155:21)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by TimothyGu** [comment]
By itself, the error output is completely correct (as demonstrated by the above CLI output). You cannot indent something if it doesn't have a parent.

However, I figured when you reported this issue it was probably something like this:

```jade
body
    script.
    $(function() {
          $("#phone").mask("(999) 999-9999");
    });
```

Which outputs this:

```
Warning: missing space before text for line 3 of jade file "undefined"   //< HERE

/home/timothy_gu/jade/lib/runtime.js:231
  throw err;
        ^
Error: Jade:4
    2|     script.
    3|     $(function() {
  > 4|           $("#phone").mask("(999) 999-9999");
    5|     });
    6| 
    7| 

unexpected token "indent"
    at Parser.parseExpr (/home/timothy_gu/jade/lib/parser.js:252:15)
    at Parser.block (/home/timothy_gu/jade/lib/parser.js:707:25)
    at Parser.tag (/home/timothy_gu/jade/lib/parser.js:816:24)
    at Parser.parseTag (/home/timothy_gu/jade/lib/parser.js:737:17)
    at Parser.parseExpr (/home/timothy_gu/jade/lib/parser.js:211:21)
    at Parser.parse (/home/timothy_gu/jade/lib/parser.js:122:25)
    at parse (/home/timothy_gu/jade/lib/index.js:102:21)
    at Object.exports.compile (/home/timothy_gu/jade/lib/index.js:177:16)
    at Socket.<anonymous> (/home/timothy_gu/jade/bin/jade.js:155:21)
    at Socket.EventEmitter.emit (events.js:117:20)
```

Again, completely correct.

Closing.
