### ISSUE TITLE
Can't render a tag beginning with "default"

### ISSUE THREAD

**Issue by s100** [jadejs/jade#1750]
When trying to use Jade to render XML containing a tag whose name begins with the string `default`, an error occurs. `default` is a Jade keyword but this happens even if the tag is something longer like `defaultBlah`. Other Jade keywords seem unaffected. This is the Node.js REPL:

    > jade.render("case");
    '<case></case>'
    > jade.render("when");
    '<when></when>'

But:

    > jade.render("default");
    Error: Jade:1
      > 1| default
    
    unexpected token "default"
        at Parser.parseExpr (C:\...\node_modules\jade\lib\parser.js:252:15)
        at Parser.parse (C:\...\node_modules\jade\lib\parser.js:122:25)
        at parse (C:\...\node_modules\jade\lib\jade.js:95:21)
        at Object.exports.compile (C:\...\node_modules\jade\lib\jade.js:161:16)
        at Object.exports.render (C:\...\node_modules\jade\lib\jade.js:299:15)
        at repl:1:6
        at REPLServer.self.eval (repl.js:110:21)
        at repl.js:249:20
        at REPLServer.self.eval (repl.js:122:7)
        at Interface.<anonymous> (repl.js:239:12)

Also:

    > jade.render("defaultFoo");
    Error: Jade:1
      > 1| defaultFoo
    
    unexpected token "default"
        at Parser.parseExpr (C:\...\node_modules\jade\lib\parser.js:252:15)
        at Parser.parse (C:\...\node_modules\jade\lib\parser.js:122:25)
        at parse (C:\...\node_modules\jade\lib\jade.js:95:21)
        at Object.exports.compile (C:\...\node_modules\jade\lib\jade.js:161:16)
        at Object.exports.render (C:\...\node_modules\jade\lib\jade.js:299:15)
        at repl:1:6
        at REPLServer.self.eval (repl.js:110:21)
        at repl.js:249:20
        at REPLServer.self.eval (repl.js:122:7)
        at Interface.<anonymous> (repl.js:239:12)

**Comment by ForbesLindesay** [comment]
This will be fixed by jadejs/jade-lexer#4 in 2.0.0

**Comment by ForbesLindesay** [comment]
Since this is fixed in 2.0.0, I'm closing this now.

**Comment by bugs181** [comment]
How do we get 2.0.0? Can't seem to get around this issue. The website also breaks with any tags starting with the word default.
