### ISSUE TITLE
`jade -w` doesn't work under windows.

### ISSUE THREAD

**Issue by vendethiel** [jadejs/jade#1814]
if I try to run `jade --watch myfile.jade`; it'll get compiled the first time, but if I edit it further, I get this error message:

```
$ jade -w popup-test.jade

  rendered popup-test.html
TypeError: path must be a string
    at Object.fs.lstat (fs.js:656:11)
    at renderFile (%AppData%\npm\node_modules\jade\bin\jade.
js:172:6)
    at StatWatcher.<anonymous> (%AppData%\npm\node_modules\j
ade\bin\jade.js:119:11)
    at StatWatcher.EventEmitter.emit (events.js:104:17)
    at StatWatcher._handle.onchange (fs.js:1083:10)
```

**Comment by ForbesLindesay** [comment]
This is fixed on master, and hopefully I'll have a new release out in a day or so.  In the mean time you can do:

```
npm install https://github.com/jadejs/jade/archive/master.tar.gz --global
```

to get the latest development version.

**Comment by vendethiel** [comment]
Amazing, thanks!

**Comment by TimothyGu** [comment]
This is a dup of #1795.
