### ISSUE TITLE
The end of the string was reached with no closing bracket found.

### ISSUE THREAD

**Issue by iliakan** [jadejs/jade#1922]
This is the first time I see such error. 

```js
    message: The end of the string was reached with no closing bracket found.

    Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    --
    stack: Error: The end of the string was reached with no closing bracket found.

    Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
        at parseMax (/js/javascript-nodejs/node_modules/jade/node_modules/character-parser/index.js:26:13)
        at Object.Compiler.buffer (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:119:23)
        at Object.Compiler.visitText (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:521:10)
        at Object.Compiler.visitNode (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:225:37)
        at Object.Compiler.visit (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:212:10)
        at Object.Compiler.visitBlock (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:295:12)
        at Object.Compiler.visitNode (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:225:37)
        at Object.Compiler.visit (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:212:10)
        at Object.Compiler.visitMixin (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:368:16)
        at Object.Compiler.visitNode (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:225:37)
        at Object.Compiler.visit (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:212:10)
        at Object.Compiler.visitBlock (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:295:12)
        at Object.Compiler.visitNode (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:225:37)
        at Object.Compiler.visit (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:212:10)
        at Object.Compiler.visitMixin (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:368:16)
        at Object.Compiler.visitNode (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:225:37)
        at Object.Compiler.visit (/js/javascript-nodejs/node_modules/jade/lib/compiler.js:212:10)
```

**Comment by iliakan** [comment]
P.S. Using jade from git, reinstalled modules yesterday. Will use published version now.

**Comment by iliakan** [comment]
P.P.S. Tried in 1.9.2 - the same.

The template was mangled, something like:
```
+e.value Created #{moment(profileUser.created).format('DD.MM.YY LT')
```

(Note, no closing `}`)

Probably the error is meant to be handled more elegantly.

**Comment by ForbesLindesay** [comment]
Thanks for reporting this!

The error message is as it should be, but we should be able to tell you the line number and filename of the jade that contains the error.  We'll make sure this gets fixed in a future version of jade.

**Comment by TimothyGu** [comment]
+1, plus the internal error notice should be removed as well since it clearly is not an internal error.

**Comment by ForbesLindesay** [comment]
@TimothyGu it is an internal error, in so much as it failed to give the line number and filename.  We auto-add the internal error text whenever we screw up by not adding that debugging info.

**Comment by TimothyGu** [comment]
@ForbesLindesay Oh OK. Seems like I forgot about #1807…

**Comment by EverettQuebral** [comment]
Do you have any timeline when 2.0.0 will be released?
