### ISSUE TITLE
Cannot create self-closing tag with &attributes

### ISSUE THREAD

**Issue by alvoro** [jadejs/jade#1923]
Template

    - var attrs = {type: "checkbox"};
    foo&attributes(attrs)/

throw

    Error: /var/www/adev/views/templates/form.jade:2
        1| - var attrs = {type: "checkbox"};
      > 2| foo&attributes(attrs)/

    unexpected text /
        at Object.Lexer.fail (/var/www/adev/node_modules/jade/lib/lexer.js:871:11)
        at Object.Lexer.next (/var/www/adev/node_modules/jade/lib/lexer.js:930:15)
        at Object.Lexer.lookahead (/var/www/adev/node_modules/jade/lib/lexer.js:113:46)
        at Parser.lookahead (/var/www/adev/node_modules/jade/lib/parser.js:102:23)
        at Parser.peek (/var/www/adev/node_modules/jade/lib/parser.js:79:17)
        at Parser.tag (/var/www/adev/node_modules/jade/lib/parser.js:752:22)
        at Parser.parseTag (/var/www/adev/node_modules/jade/lib/parser.js:738:17)
        at Parser.parseExpr (/var/www/adev/node_modules/jade/lib/parser.js:211:21)
        at Parser.parse (/var/www/adev/node_modules/jade/lib/parser.js:122:25)
        at Parser.parseInclude (/var/www/adev/node_modules/jade/lib/parser.js:595:22)

**Comment by TimothyGu** [comment]
Do this:

```jade
- var attrs = {type: "checkbox"};
foo/&attributes(attrs)
```

**Comment by alvoro** [comment]
@TimothyGu  , thanks
