### ISSUE TITLE
don't fail on unicode js newlines (\u2028, \u2029) when using -O with a JSON string

### ISSUE THREAD

**Issue by jurriaan** [jadejs/jade#1949]
```
SyntaxError: Unexpected token ILLEGAL
    at parseObj (/usr/local/lib/node_modules/jade/bin/jade.js:77:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/jade/bin/jade.js:65:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

This is because of the eval in https://github.com/jadejs/jade/blob/master/bin/jade.js#L78. Instead of eval the object should be parsed using JSON.parse.

**Comment by ForbesLindesay** [comment]
The downside is that using JSON.parse does not support nearly as much functionality as eval does.

**Comment by ForbesLindesay** [comment]
Moving to jade-cli
