### ISSUE TITLE
Unclear error with inline JS

### ISSUE THREAD

**Issue by aug-riedinger** [jadejs/jade#1963]
I just updated my jade from 0.4 to 1.10. I keep having error on my inline JS scripts. First thing is, I don't find any error there, second thing is, even if there are some, they are crazy hard to debug. Final point is why should jade care about the correctness of my inline JS?

Here is the error: 

```
SyntaxError: /home/augustin/Workspace/augustin-riedinger/views/layout.jade:89
    87| 									(function(d, s, id) {
    88| 									var js, fjs = d.getElementsByTagName(s)[0];
  > 89| 									if (d.getElementById(id)) return;
    90| 									js = d.createElement(s); js.id = id;
    91| 									js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=129366813919453";
    92| 									fjs.parentNode.insertBefore(js, fjs);

Unexpected token ;
    at Function (<anonymous>)
    at assertExpression (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:30:3)
    at Object.Lexer.attrs (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:661:20)
    at Object.Lexer.next (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:922:15)
    at Object.Lexer.lookahead (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:79:17)
    at Parser.block (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:704:30)
    at Parser.tag (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:817:24)
    at Parser.parseTag (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:738:17)
```

And the jade:

```
			if social
				.dark-wrapper
					.inner
						.flt-rght.one-third.center.last
							h3 Share
							ul
								li
									.fb-like(data-send='true', data-width='200')

								#fb-root
								script
									(function(d, s, id) {
									var js, fjs = d.getElementsByTagName(s)[0];
									if (d.getElementById(id)) return;
									js = d.createElement(s); js.id = id;
									js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=129366813919453";
									fjs.parentNode.insertBefore(js, fjs);
									}(document, 'script', 'facebook-jssdk'));

								li
									a(href='https://twitter.com/share', class='twitter-share-button', data-via='Aug_Riedinger', data-lang='#{lang}', data-size='large', data-count='none', data-text='#{title}') Tweet

								script
									!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

						.flt-rght.two-third
							#disqus_thread
								script(type='text/javascript')
									var disqus_shortname = 'portfolio-ar'; 
									(function() {
									var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
									dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
									(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
									})();
								noscript
									| Please enable JavaScript to view the
									a(href='http://disqus.com/?ref_noscript') Comments powered by Disqus.
								a.dsq-brlink(href='http://disqus.com')
									| comments powered by
									span.logo-disqus Disqus
						.clear	

```

I have tried many variations (commenting, deleting rows etc.) without success. 

Thanks

**Comment by ForbesLindesay** [comment]
This change was made in 0.31.0 (see [the changelog](https://github.com/jadejs/jade/blob/master/History.md#0310--2013-05-30).  It is not attempting to validate your JavaScript.  Before 0.31.0, script and style tags were implicitly text-only.  This meant that you couldn't do a lot of useful things like:

```jade
script
  include ./my-script.js
```


The upshot of this change is that you must put a `.` after any inline script or style tag to mark the contents as text-only.  e.g.

```jade
            if social
                .dark-wrapper
                    .inner
                        .flt-rght.one-third.center.last
                            h3 Share
                            ul
                                li
                                    .fb-like(data-send='true', data-width='200')

                                #fb-root
                                script.
                                    (function(d, s, id) {
                                    var js, fjs = d.getElementsByTagName(s)[0];
                                    if (d.getElementById(id)) return;
                                    js = d.createElement(s); js.id = id;
                                    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=129366813919453";
                                    fjs.parentNode.insertBefore(js, fjs);
                                    }(document, 'script', 'facebook-jssdk'));

                                li
                                    a(href='https://twitter.com/share', class='twitter-share-button', data-via='Aug_Riedinger', data-lang='#{lang}', data-size='large', data-count='none', data-text='#{title}') Tweet

                                script.
                                    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

                        .flt-rght.two-third
                            #disqus_thread
                                script(type='text/javascript').
                                    var disqus_shortname = 'portfolio-ar'; 
                                    (function() {
                                    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                                    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                                    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
                                    })();
                                noscript
                                    | Please enable JavaScript to view the
                                    a(href='http://disqus.com/?ref_noscript') Comments powered by Disqus.
                                a.dsq-brlink(href='http://disqus.com')
                                    | comments powered by
                                    span.logo-disqus Disqus
                        .clear  
```

**Comment by aug-riedinger** [comment]
Sorry, I forgot to mention that I tried with the dots also (been trying several configuration hence whent back to original to report the issue).

But the error message changed, that's right:

```
Error: /home/augustin/Workspace/augustin-riedinger/views/layout.jade:97
    95| 								li
    96| 									a(href='https://twitter.com/share', class='twitter-share-button', data-via='Aug_Riedinger', data-lang='#{lang}', data-size='large', data-count='none', data-text='#{title}') 
  > 97| 										| Tweet
    98| 
    99| 								script.
    100| 									!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');

unexpected text 	

		
    at Object.Lexer.fail (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:871:11)
    at Object.Lexer.next (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:930:15)
    at Object.Lexer.lookahead (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:79:17)
    at Parser.tag (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:752:22)
    at Parser.parseTag (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:738:17)
    at Parser.parseExpr (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:250:21)
    at Parser.block (/home/augustin/Workspace/augustin-riedinger/node_modules/jade/lib/parser.js:708:25)
```

Apparently, concerning those lines:

```
								li
									a(href='https://twitter.com/share', class='twitter-share-button', data-via='Aug_Riedinger', data-lang='#{lang}', data-size='large', data-count='none', data-text='#{title}') Tweet

```

**Comment by ForbesLindesay** [comment]
I'm unable to reproduce that error.  If you can provide me with some jade that actually produces the error, I can look into it.
