### ISSUE TITLE
Missing space before text

### ISSUE THREAD

**Issue by mnzt** [jadejs/jade#1964]
jQuery will only fire when all lines are at an equal tab distance, example:

    script(type='text/javascript')
      $(document).ready(function() {
      $("#toggleSidebar").click(function() {
      $('.ui.wide.left.vertical.labeled.icon.sidebar.menu').sidebar('toggle');
      });
      $("#toggleLogout").click(function() {
      $('.small.modal').modal('show');
      });
    });

But when indenting the code by 2-space tabs, it throws out this error:

Error: c:\Users\mnzt\code\learning\G27Films\views\layout.jade:14
   12|     script(type='text/javascript')
   13|       $(document).ready(function() {
  -> 14|         $("#toggleSidebar").click(function() {
   15|       $('.ui.wide.left.vertical.labeled.icon.sidebar.menu').sidebar('toggle');
   16|       });
   17|       $("#toggleLogout").click(function() {

unexpected token "indent"
   at Parser.parseExpr (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:252:15)
   at Parser.block (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:708:25)
   at Parser.tag (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:817:24)
   at Parser.parseTag (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:738:17)
   at Parser.parseExpr (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:211:21)
   at Parser.block (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:708:25)
   at Parser.tag (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:817:24)
   at Parser.parseTag (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:738:17)
   at Parser.parseExpr (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:211:21)
   at Parser.block (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:708:25)
   at Parser.tag (c:\Users\mnzt\code\learning\x\node_modules\jade\lib\parser.js:817:24)

**Comment by TimothyGu** [comment]
Use <code>script(type='text/javascript')<strong>.</strong></code>: ← with the dot

```jade
script(type='text/javascript').
  $(document).ready(function() {
    $("#toggleSidebar").click(function() {
      $('.ui.wide.left.vertical.labeled.icon.sidebar.menu').sidebar('toggle');
    });
    $("#toggleLogout").click(function() {
      $('.small.modal').modal('show');
    });
  });
```
