### ISSUE TITLE
Rendering a locals Object throws undefined error inside href attr - ex a(href=locals.myObject.attribute)

### ISSUE THREAD

**Issue by mikeuduc** [jadejs/jade#1985]
When setting a js Object to the locals variable, Jade throws an undefined error when trying to access object attributes inside a link <a> href attribute.  Even through it throws an error, the href attribute still renders the object attribute (ie - it's NOT undefined). 

I set the local variable currentCompany (currentCompany is an object)
```javascript
res.locals.currentCompany = req.currentCompany;
```

In my jade template, the following throws the error "Cannot read property 'uid' of undefined"

```jade
a(href=locals.currentCompany.uid + '/people')
```

The following also throws an undefined error:
```jade
a(href='#{locals.currentCompany.uid}/people')
```
[Screenshot of error] (http://cl.ly/image/0o3T001g2d0f)
***Note***: The link is displayed correctly even though an error is thrown.

Also, jade throws no errors when rendering the locals.object.attribute inside html elements. The following does NOT throw and error, and it displays the uid correctly.
```jade
div #{locals.currentCompany.uid}
```

Am I doing something wrong?

**Environment:**
Node v0.10.33
Jade@1.10.0

**Comment by alubbe** [comment]
Try using just currentCompany.uid. jade namescopes your local variables, so
you don't need to use the locals. prefix.
Am 07.06.2015 23:54 schrieb "mikeuduc" <notifications@github.com>:

**Comment by ForbesLindesay** [comment]
I'll need to see the actual error message (complete with stack trace) to be able to help here.

**Comment by mikeuduc** [comment]
@ForbesLindesay Here ya go.

```
TypeError: /Users/michael/Development/crew/views/_layout.jade:33
    31|               a(href='#')
    32|                 span.glyphicon.glyphicon-stats
  > 33|                 |  Reports
    34|             li
    35|               a(href="/#{locals.currentCompany.uid}/people")
    36|                 span.glyphicon.glyphicon-user

Cannot read property 'uid' of undefined
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:160:64)
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:507:22)
    at res (/Users/michael/Development/crew/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/Users/michael/Development/crew/node_modules/jade/lib/index.js:417:11)
    at View.render (/Users/michael/Development/crew/node_modules/express/lib/view.js:93:8)
    at EventEmitter.app.render (/Users/michael/Development/crew/node_modules/express/lib/application.js:566:10)
    at ServerResponse.res.render (/Users/michael/Development/crew/node_modules/express/lib/response.js:938:7)
    at /Users/michael/Development/crew/lib/init-errors.js:30:9
    at Layer.handle_error (/Users/michael/Development/crew/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:300:13)
    at /Users/michael/Development/crew/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:321:12)
    at IncomingMessage.next (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:261:10)
    at fn (/Users/michael/Development/crew/node_modules/express/lib/response.js:933:25)
```

**Comment by mikeuduc** [comment]
@alubbe I tried that as well. I still get the same error, yet the uid is rendered correctly.
```
res.render('app/company', { 
     currentCompany: req.currentCompany
});
```

```
a(href="/#{currentCompany.uid}/people")
```

**Comment by ForbesLindesay** [comment]
My guess would be that the first call is working properly and then the client is requesting a url that you don't expect it to (e.g. you will get a request for `/favicon.ico`) and it is this unexpected request that is throwing an error.

Try replacing

```js
res.render('app/company', { 
     currentCompany: req.currentCompany
});
```

with

```js
console.log('url:');
console.dir(req.url);
console.log('current company:');
console.dir(req.currentCompany);
res.render('app/company', { 
     currentCompany: req.currentCompany
});
```

My guess is you will se something like:

```
url:
'/my-page'
current company:
{uid: 'my-company-id'}
url:
'/favicon.ico'
current company:
undefined
TypeError: /Users/michael/Development/crew/views/_layout.jade:33
    31|               a(href='#')
    32|                 span.glyphicon.glyphicon-stats
  > 33|                 |  Reports
    34|             li
    35|               a(href="/#{locals.currentCompany.uid}/people")
    36|                 span.glyphicon.glyphicon-user

Cannot read property 'uid' of undefined
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:160:64)
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:507:22)
    at res (/Users/michael/Development/crew/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/Users/michael/Development/crew/node_modules/jade/lib/index.js:417:11)
    at View.render (/Users/michael/Development/crew/node_modules/express/lib/view.js:93:8)
    at EventEmitter.app.render (/Users/michael/Development/crew/node_modules/express/lib/application.js:566:10)
    at ServerResponse.res.render (/Users/michael/Development/crew/node_modules/express/lib/response.js:938:7)
    at /Users/michael/Development/crew/lib/init-errors.js:30:9
    at Layer.handle_error (/Users/michael/Development/crew/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:300:13)
    at /Users/michael/Development/crew/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:321:12)
    at IncomingMessage.next (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:261:10)
    at fn (/Users/michael/Development/crew/node_modules/express/lib/response.js:933:25)
```

as the logs.

P.S. you can use just `currentCompany.uid` in your template even with the `res.locals.currentCompany = foo` style of setting locals.

**Comment by mikeuduc** [comment]
@ForbesLindesay - it's really quite strange. There doesn't seem to be a 2nd request. Here is my entire console output from restarting the app.

```
michaels-air-2:crew michael$ PORT=8000 node app.js
GET /V1gLSyhTH 302 15.729 ms - 58
GET / 302 3.135 ms - 68
GET /login 200 390.880 ms - 1432
GET /css/bootstrap.min.css 304 5.854 ms - -
GET /css/style.css 304 5.291 ms - -
GET /css/login-style.css 304 2.299 ms - -
GET /images/symbol.svg 304 1.770 ms - -
GET /js/jquery-1.10.2.min.js 304 1.608 ms - -
GET /js/bootstrap.min.js 304 1.917 ms - -
POST /login 302 115.296 ms - 58
GET / 302 4.619 ms - 76
url:
'/E1edZroRr'
current company:
{ _id: 5575b61e39b3abde0741f3a5,
  uid: 'E1edZroRr',
  role: 'owner',
  name: 'My Test Company',
  joined: Mon Jun 08 2015 11:34:54 GMT-0400 (EDT),
  _blasts: [] }
GET /E1edZroRr 304 168.811 ms - -
GET /css/bootstrap.min.css 304 1.305 ms - -
GET /css/style.css 304 2.814 ms - -
GET /images/crewfire-logo.svg 304 2.487 ms - -
GET /js/jquery-1.10.2.min.js 304 2.165 ms - -
GET /js/bootstrap.min.js 304 4.523 ms - -
GET /images/tw.png 304 1.533 ms - -
GET /images/fb.png 304 2.592 ms - -
GET /images/example.png 304 4.611 ms - -
TypeError: /Users/michael/Development/crew/views/_layout.jade:33
    31|               a(href='#')
    32|                 span.glyphicon.glyphicon-stats
  > 33|                 |  Reports
    34|             li
    35|               a(href="/#{currentCompany.uid}/people")
    36|                 span.glyphicon.glyphicon-user

Cannot read property 'uid' of undefined
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:160:57)
    at eval (eval at <anonymous> (/Users/michael/Development/crew/node_modules/jade/lib/index.js:218:8), <anonymous>:507:22)
    at res (/Users/michael/Development/crew/node_modules/jade/lib/index.js:219:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:380:38)
    at Object.exports.renderFile (/Users/michael/Development/crew/node_modules/jade/lib/index.js:370:21)
    at View.exports.__express [as engine] (/Users/michael/Development/crew/node_modules/jade/lib/index.js:417:11)
    at View.render (/Users/michael/Development/crew/node_modules/express/lib/view.js:93:8)
    at EventEmitter.app.render (/Users/michael/Development/crew/node_modules/express/lib/application.js:566:10)
    at ServerResponse.res.render (/Users/michael/Development/crew/node_modules/express/lib/response.js:938:7)
    at /Users/michael/Development/crew/lib/init-errors.js:30:9
    at Layer.handle_error (/Users/michael/Development/crew/node_modules/express/lib/router/layer.js:58:5)
    at trim_prefix (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:300:13)
    at /Users/michael/Development/crew/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:321:12)
    at IncomingMessage.next (/Users/michael/Development/crew/node_modules/express/lib/router/index.js:261:10)
    at fn (/Users/michael/Development/crew/node_modules/express/lib/response.js:933:25)
GET /fonts/glyphicons-halflings-regular.woff2 500 189.257 ms - 2577
GET /fonts/glyphicons-halflings-regular.woff 304 1.079 ms - -
```

**Comment by ForbesLindesay** [comment]
The important line from that log is:

```
GET /fonts/glyphicons-halflings-regular.woff2 500 189.257 ms - 2577
```

That url is somehow causing your jade template to be rendered.  Probably on line 30 of "/Users/michael/Development/crew/lib/init-errors.js".  At that point, currentCompany is no doubt undefined.

**Comment by mikeuduc** [comment]
@ForbesLindesay Genius! I removed the init-errors.js and no longer get the error.  

I greatly appreciate the help.  Very sorry for having you debug what was an application error on my part.
