### ISSUE TITLE
The end of the string was reached with no closing bracket found.

### ISSUE THREAD

**Issue by xbenjii** [jadejs/jade#1998]
Version: 1.11.0

Stack trace:
```
Error: The end of the string was reached with no closing bracket found.

Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    at parseMax (c:\njs\Texere\node_modules\jade\node_modules\character-parser\index.js:26:13)
    at Object.Compiler.buffer (c:\njs\Texere\node_modules\jade\lib\compiler.js:119:23)
    at Object.Compiler.visitText (c:\njs\Texere\node_modules\jade\lib\compiler.js:523:10)
    at Object.Compiler.visitNode (c:\njs\Texere\node_modules\jade\lib\compiler.js:225:37)
    at Object.Compiler.visit (c:\njs\Texere\node_modules\jade\lib\compiler.js:212:10)
    at Object.Compiler.visitBlock (c:\njs\Texere\node_modules\jade\lib\compiler.js:295:12)
    at Object.Compiler.visitNode (c:\njs\Texere\node_modules\jade\lib\compiler.js:225:37)
    at Object.Compiler.visit (c:\njs\Texere\node_modules\jade\lib\compiler.js:212:10)
    at Object.Compiler.visitTag (c:\njs\Texere\node_modules\jade\lib\compiler.js:480:12)
    at Object.Compiler.visitNode (c:\njs\Texere\node_modules\jade\lib\compiler.js:225:37)
    at Object.Compiler.visit (c:\njs\Texere\node_modules\jade\lib\compiler.js:212:10)
    at Object.Compiler.visitBlock (c:\njs\Texere\node_modules\jade\lib\compiler.js:295:12)
    at Object.Compiler.visitNode (c:\njs\Texere\node_modules\jade\lib\compiler.js:225:37)
    at Object.Compiler.visit (c:\njs\Texere\node_modules\jade\lib\compiler.js:212:10)
    at Object.Compiler.visitBlock (c:\njs\Texere\node_modules\jade\lib\compiler.js:295:12)
    at Object.Compiler.visitNode (c:\njs\Texere\node_modules\jade\lib\compiler.js:225:37)
    at Object.Compiler.visit (c:\njs\Texere\node_modules\jade\lib\compiler.js:212:10)
    at Object.Compiler.visitTag (c:\njs\Texere\node_modules\jade\lib\compiler.js:480:12)
```

Offending code:
``` JavaScript
$('.bootstrap-fileinput').fileinput({
    uploadUrl: '/category/#{category.id}/images',
    uploadAsync: true,
    minFileCount: 1,
    maxFileCount: 5,
    overwriteInitial: false,
    initialPreview: !{JSON.stringify(category.Images.map(function (image) {
        return '<img src="/image/' + image.id + '" class="file-preview-image">';
    }))},
    initialPreviewConfig: !{JSON.stringify(category.Images.map(function (image) {
        return {url: '/image/' + image.id + '/delete'}
    }))}
});
```

If I remove the code generating the `initialPreview` and `initialPreviewConfig` properties then it works fine.

**Comment by xbenjii** [comment]
Turns out you can't multi-line it. Closing.
