### ISSUE TITLE
Status of filters

### ISSUE THREAD

**Issue by josip** [jadejs/jade#2001]
I have noticed that my custom filters stopped working sometime after 1.9.2 and definitely do not work anymore with 1.11.0. I see that there is a plan to remove them but could the docs somewhere somehow clarify the situation?

Just to clarify, example of a filter I have:
```javascript
jade.filters.scss = function (str) {
    // do some stuff besides just running sass
   return '<style>' + css + '</style>';
}
```

With 1.11.0, I get the following error:

```
Error: .../src/blocks/html/template.jade:1
  > 1| :scss
    2|     .panel-body img {
    3|         max-width: 100%;
    4|     }

unknown filter ":scss"
    at filter (.../gulp-jade/node_modules/jade/lib/filters.js:12:11)
    at Object.Compiler.visitFilter (.../gulp-jade/node_modules/jade/lib/compiler.js:507:19)
    at Object.Compiler.visitNode (.../gulp-jade/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (.../gulp-jade/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (.../gulp-jade/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (.../gulp-jade/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (.../gulp-jade/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.compile (.../gulp-jade/node_modules/jade/lib/compiler.js:66:10)
    at parse (.../gulp-jade/node_modules/jade/lib/index.js:114:19)
    at Object.exports.compile (.../gulp-jade/node_modules/jade/lib/index.js:205:16)
```

**Comment by TimothyGu** [comment]
> I see that there is a plan to remove them but could the docs somewhere somehow clarify the situation?

We are not trying to remove them, but rather switch them to a new architecture based on JSTransformers.

> With 1.11.0, I get the following error:
> 
> ```
unknown filter ":scss"
    at filter (.../gulp-jade/node_modules/jade/lib/filters.js:12:11)
```

This doesn't look like 1.11.0, since in 1.11.0 the error would be thrown at line 97 rather than 12.

And, I cannot reproduce the issue with the following snippet, with Jade 1.11.0:

```js
var jade = require('jade')
jade.filters.scss = function (str) {
  return '<style>' + str + '</style>'
}
console.log(jade.render(':scss\n  #myId {\n    padding: 0;\n  }'))
```

It correctly outputs:

```html
<style>#myId {
  padding: 0;
}</style>
```

**Comment by TimothyGu** [comment]
Seeing that you are using gulp-jade, the Gulp plugin must be using a different version of jade than the one whose `.filters` you have modified.

**Comment by josip** [comment]
That was it... sorry for the issue, I wasn't paying attention to the log at all. :coffee: time
