### ISSUE TITLE
Syntax errors could be more concise

### ISSUE THREAD

**Issue by robbyoconnor** [jadejs/jade#2012]
Currently there are zero tools for syntax checking for neither vim nor emacs. I suspect the reason why is this lovely output: 

```
/home/rob/.nvm/v0.10.35/lib/node_modules/jade/lib/runtime.js:231
  throw err;
        ^
Error: test.jade:2
    1|    doctype html
  > 2|  html
    3|   head
    4|     title Jade Examples
    5|     body

unexpected token "indent"
    at Parser.parseExpr (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/lib/parser.js:252:15)
    at Parser.parse (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/lib/parser.js:122:25)
    at parse (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/lib/index.js:205:16)
    at renderFile (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/bin/jade.js:227:71)
    at Array.forEach (native)
    at Object.<anonymous> (/home/rob/.nvm/v0.10.35/lib/node_modules/jade/bin/jade.js:132:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

There is information that isn't relevant here: I don't need a stack trace for code that I don't even own.

What you could do: 
```
Error: unexpected token "indent" in test.jade:2 
    1|    doctype html
  > 2|  html
    3|   head
    4|     title Jade Examples
    5|     body
```
The current error messages are nice for humans, ugly for computers to parse.  The way I proposed is actually nicer for humans *AND* computers alike! Be even better if you just didn't include the 5 lines at all, and then I can parse this with no issues.

**Comment by robbyoconnor** [comment]
bump.

**Comment by TimothyGu** [comment]
Work is being done to error handling for Jade in general in https://github.com/jadejs/jade-error. I'm going to close this issue and reopen a corresponding one in jade-error instead.

**Comment by TimothyGu** [comment]
See jadejs/jade-error#1.
