### ISSUE TITLE
less >2 support

### ISSUE THREAD

**Issue by OEvgeny** [jadejs/jade#2054]
Still can't include less files with less > 2 version.
```
app_1 |     23|     style
app_1 |   > 24|       include:less ./less/loader.less
app_1 | 
app_1 | Cannot read property 'contents' of undefined
app_1 |     at Object.Parser.parse (/app/node_modules/less/lib/less/parser/parser.js:117:20)
app_1 |     at Transformer.exports.less.Transformer.async [as _renderAsync] (/app/node_modules/jade/node_modules/transformers/lib/transformers.js:363:12)
app_1 |     at Transformer.renderSync (/app/node_modules/jade/node_modules/transformers/lib/shared.js:87:10)
app_1 |     at filter (/app/node_modules/jade/lib/filters.js:91:33)
app_1 |     at Parser.parseInclude (/app/node_modules/jade/lib/parser.js:596:13)
app_1 |     at Parser.parseExpr (/app/node_modules/jade/lib/parser.js:223:21)
app_1 |     at Parser.block (/app/node_modules/jade/lib/parser.js:729:25)
app_1 |     at Parser.tag (/app/node_modules/jade/lib/parser.js:838:24)
app_1 |     at Parser.parseTag (/app/node_modules/jade/lib/parser.js:759:17)
app_1 |     at Parser.parseExpr (/app/node_modules/jade/lib/parser.js:211:21)
```
Looks like it's not supported (I'm using ``"less": "^2.5.1"``)

Seems it`s related to #1799

**Comment by ForbesLindesay** [comment]
If you are using jade@1.11.0 you can migrate to jstransformers (which will be required when you upgrade to 2.0.0).  Simply install `jstransformer-less` instead of `less`, and it should work fine.  This will use the latest version of less.

**Comment by OEvgeny** [comment]
Oh thanks, good to know!
