### ISSUE TITLE
Lexer trying to parse plain text includes

### ISSUE THREAD

**Issue by RobertWHurst** [jadejs/jade#2066]
I'm trying to include some css, and it seems jade tries to handle it as a jade file.

```jade
doctype html
html(lang='en')
  head
    meta(http-equiv='Content-Type', content='text/html; charset=UTF-8')
    meta(name='viewport', content='width=device-width; initial-scale=1.0; maximum-scale=1.0;')
    title= subject
    style
      include default.css
```

```
Error: /Users/.../template/default.css:4
    2| body {
    3|   width: 100%;
  > 4|   background-color: #F1F2F7;
    5|   margin: 0;
    6|   padding: 0;
    7|   -webkit-font-smoothing: antialiased;

unexpected text ;
  m
    at Object.Lexer.fail (/Users/.../node_modules/jade/lib/lexer.js:887:11)
    at Object.Lexer.next (/Users/.../node_modules/jade/lib/lexer.js:947:15)
    at Object.Lexer.lookahead (/Users/.../node_modules/jade/lib/lexer.js:113:46)
    at Parser.lookahead (/Users/.../node_modules/jade/lib/parser.js:102:23)
    at Parser.peek (/Users/.../node_modules/jade/lib/parser.js:79:17)
    at Parser.tag (/Users/.../node_modules/jade/lib/parser.js:773:22)
    at Parser.parseTag (/Users/.../node_modules/jade/lib/parser.js:759:17)
    at Parser.parseExpr (/Users/.../node_modules/jade/lib/parser.js:211:21)
    at Parser.parseExpr (/Users/.../node_modules/jade/lib/parser.js:252:21)
    at Parser.tag (/Users/.../node_modules/jade/lib/parser.js:819:29)
```

I'm using jade@1.11.0

**Comment by TimothyGu** [comment]
I cannot reproduce this bug at all.

Can you please put a self-contained example on GitHub or Gists?

**Comment by ForbesLindesay** [comment]
Please update to the latest version of jade and see if you still experience the issue.

**Comment by RobertWHurst** [comment]
@TimothyGu I'll add a zip of the offending code. I did notice that this does work if I change the code. Seems to only happen with a select arrangement of html. @ForbesLindesay Will do later today, thanks :)

**Comment by RobertWHurst** [comment]
@TimothyGu @ForbesLindesay, Turned out to be an issue in the project. Someone was doing some monkey patching that broke Jade. Sorry gents.
