### ISSUE TITLE
Unexpected token "intedent"

### ISSUE THREAD

**Issue by G07cha** [jadejs/jade#2097]
```bash
❯ cat public/index.html | jade
/usr/local/lib/node_modules/jade/lib/runtime.js:240
  throw err;
        ^
Error: Jade:3
    1| <!DOCTYPE html>
    2| <html>
  > 3| 	<head>
    4| 		<title>Twitter collage</title>
    5| 		<link rel="icon" type="image/ico" href="twitter.ico">
    6| 		<script src='js/main.js'></script>

unexpected token "indent"
    at Parser.parseExpr (/usr/local/lib/node_modules/jade/lib/parser.js:254:15)
    at Parser.parse (/usr/local/lib/node_modules/jade/lib/parser.js:122:25)
    at parse (/usr/local/lib/node_modules/jade/lib/index.js:104:21)
    at Object.exports.compile (/usr/local/lib/node_modules/jade/lib/index.js:205:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/jade/bin/jade.js:201:21)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

File and versions you can find in #2096

**Comment by TimothyGu** [comment]
It was fixed in Jade master branch.
