### ISSUE TITLE
Is for/each broken in the latest jade? 

### ISSUE THREAD

**Issue by jichifly** [jadejs/jade#2153]
I installed jade by "npm install jade", and found the for/each syntax does not work.
Here's a test file I tried:

    - var l = [1,2,3];
    ul
      for book in l
        li= book
      else
        li sorry, no books!

It worked in jade@1.7.0 and before, but would raise exception in acorn module in jade@1.8.0, 1.9.0, 1.10.0, and 1.11.0.
Tried on both Mac with nodejs 2.14.8 and Ubuntu with nodejs 2.11.3.
Here's the error I got when running in terminal.

    % jade a.jade
    /Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1747
      throw err;
      ^
    
    SyntaxError: Unexpected token (1:11)
        at Parser.pp.raise (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1745:13)
        at Parser.pp.unexpected (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2264:8)
        at Parser.pp.parseBindingAtom (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1876:12)
        at Parser.pp.parseMaybeDefault (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1920:23)
        at Parser.pp.parseBindingList (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1896:23)
        at Parser.pp.parseFunctionParams (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2776:22)
        at Parser.pp.parseFunction (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:2769:8)
        at Parser.pp.parseExprAtom (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1129:19)
        at Parser.pp.parseExprSubscripts (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1023:19)
        at Parser.pp.parseMaybeUnary (/Users/jichi/node_modules/jade/node_modules/with/node_modules/acorn/dist/acorn.js:1004:19)

The other syntax such as if-else conditions, block/extends, and even "- for (var ...)" work.
But bare "for" and "each" do not work.
Also tried invoking jade from Express instead of from command line, but got the same acorn exception.

**Comment by TimothyGu** [comment]
Investigating

**Comment by TimothyGu** [comment]
Fixed in ForbesLindesay/acorn-globals@960a7bb77382d5f1874d885eae5efdade88556e1. Thanks for reporting!
