### ISSUE TITLE
Error: input is self closing and should not have content.

### ISSUE THREAD

**Issue by knotech** [jadejs/jade#2178]
So here's the code I was trying to run:

`ul`
`	each account in accountlist`
`		li(class='no-bullets'): form(id='get-account-info'): input(type='hidden', name= account): button(class='btn', action='submit')= account`

The indentation is right, I'm just too tired to pull up the markdown cheatsheet right now.

It worked fine until I nested the input element.

I'm making a assumption that this is either because I was trying to use the account element of the array twice, or that my syntax within input field was off; that an attribute doesn't read a value the same way, and I simply can't find anything on it anywhere else. I'm not above being wrong or misinformed, in fact when I'm coding I feel like I'm both, most of the time. 

Here's the stack trace the error message asked me to pass on, including the message to pass the message on. You know, because meta.

`Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
     at Object.Compiler.visitTag (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:471:32)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitBlock (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:295:12)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitTag (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:480:12)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitBlock (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:295:12)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitTag (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:480:12)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitBlock (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:295:12)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitEach (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:609:10)
   at Object.Compiler.visitNode (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:225:37)
   at Object.Compiler.visit (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:212:10)
   at Object.Compiler.visitBlock (/Users/knotech/myproject/node_modules/jade/lib/compiler.js:295:12)

**Comment by knotech** [comment]
My bad, inputs can't have children.

I nested the button.

**Comment by ForbesLindesay** [comment]
Is there anything you can suggest that would make it clearer why you were getting this error message?  Perhaps you could submit a pull request to improve the error we output in this case: https://github.com/jadejs/jade-code-gen/blob/6f4ebc04ea1833ca477a098504c6ebeeb0778eae/index.js#L563

**Comment by knotech** [comment]
Sent a pull request. It was a rookie mistake. Making the transition to jade, the idea of closing tags kind of disappears into the indentation, and I neglect to consider that it outputs HTML. At least that's been my wonderful experience.

Seriously, thank you for your Herculean effort with this lib. It's saved me whole days of life in typing.
