### ISSUE TITLE
Error: The end of the string was reached with no closing bracket found.

### ISSUE THREAD

**Issue by fschwehn** [jadejs/jade#4]
Error: The end of the string was reached with no closing bracket found.

Please report this entire error and stack trace to https://github.com/jadejs/jade/issues
    at parseMax (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/node_modules/character-parser/index.js:26:13)
    at Object.Compiler.buffer (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:119:23)
    at Object.Compiler.visitText (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:523:10)
    at Object.Compiler.visitNode (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitTag (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:480:12)
    at Object.Compiler.visitNode (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:225:37)
    at Object.Compiler.visit (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:212:10)
    at Object.Compiler.visitBlock (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:295:12)
    at Object.Compiler.visitNode (/Users/fschwehn/iosxpert/workspace/ioproductcenter/node_modules/jade/lib/compiler.js:225:37)

**Comment by niftylettuce** [comment]
see https://github.com/pugjs/jade/issues/2184
