### ISSUE TITLE
Better error handling for malformed javascript

### ISSUE THREAD

**Issue by ForbesLindesay** [jadejs/jade#856]
```jade
doctype html
html(lang="en")
  head
    - function bar() {
      script
        var foo = 10;
    - bar();
  body
    p the body
```

Results in:

```
SyntaxError: Unexpected token catch
    at Object.Function (unknown source)
    at Object.exports.compile (C:\Users\Forbes\AppData\Roaming\npm\node_modules\jade\lib\jade.js:176:8)
    at Object.exports.render (C:\Users\Forbes\AppData\Roaming\npm\node_modules\jade\lib\jade.js:215:17)
    at Object.exports.renderFile (C:\Users\Forbes\AppData\Roaming\npm\node_modules\jade\lib\jade.js:243:13)
    at exports.jade
```

even if it's rendered with a filename.

We should at the very least make it `'Unexpected token catch while compiling  ' + (options.filename || 'jade template)`

**Comment by ForbesLindesay** [comment]
Error handling can be reviewed after the 2.0.0 release.
